### ISSUE TITLE
future to-do for nr-reporting-summary.pdf

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#99]
- [x] ~~provide more details on dendro band sampling strategy at SCBI (ask Sean)~~ - on a re-read, I think this is okay.
- [x] get more details on tree ring sampling from coauthors
- [x] add randomization info for tree ring sampling

**Comment by teixeirak** [comment]
Statements in nr-reporting-summary for **106 tree-ring only sites**

## Sampling strategy 

The tree-ring records from our focal sites were complemented with a much larger collection of tree-ring chronologies spanning 106 deciduous and mixed forest sites in Eastern North America (see Maxwell et al. 2020; https://doi.org/10.5194/cp-16-1901-2020).

## Data collection

All tree cores had been previously collected, cross-dated, and measured using standard collection and processing methodologies. Details are provided in the original publications cited in the manuscript.

## Randomization

(no statement)
